version: '3.8'

# Включение proxy.yaml
include:
  - ./proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: on-failure
    environment:
      DB_HOST: 172.20.0.10
      DB_USER: root
      DB_PASSWORD: very_strong
      DB_NAME: example
      DB_PORT: 3306
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: very_strong
      MYSQL_USER: app
      MYSQL_PASSWORD: very_strong
      MYSQL_DATABASE: example
    ports:
      - "3307:3306"
    volumes:
      - ./var/lib/mysql:/var/lib/mysql

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  db_data:
